apiVersion: v1
kind: Service
metadata:
  name: drill-db-service
  namespace: drill
spec:
  selector:
    app: drill-db
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 32336