apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-drill-db-root-password
  namespace: drill
spec:
  type: kv-v2
  mount: kv
  path: secret/kubernetes/drill/db/root
  destination:
    name: drill-db-root-password
    create: true
    type: Opaque
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        "root-password":
          text: >-
            {{ .Secrets.password }}
  refreshAfter: 30s
  vaultAuthRef: static-auth