apiVersion: v1
kind: PersistentVolume
metadata:
  name: drill-db-pv-volume
  labels:
    type: local
spec:
  claimRef:
    name: drill-db-pv-claim
    namespace: drill
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/douglas444/nfs-storage/drill-db_data
    server: blindspot.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drill-db-pv-claim
  namespace: drill
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
