---
# Cluster role with all the access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nexus-admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
# Service account with the name jenkins-admin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexus-admin
  namespace: nexus
---
# cluster role binding combining cluster role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nexus-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nexus-admin
subjects:
- kind: ServiceAccount
  name: nexus-admin
  namespace: nexus