apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
spec:
  selector:
      app: nexus-registry
  type: NodePort
  ports:
  - name: httpport
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 33000