apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv-volume
  labels:
      name: local
spec:
  claimRef:
    name: nexus-pv-claim
    namespace: nexus
  capacity:
      storage: 40Gi
  accessModes:
      - ReadWriteOnce
  nfs:
    path: /home/douglas444/nfs-storage/nexus_data
    server: blindspot.local

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pv-claim
  namespace: nexus
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi