version: "2.1"
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - /home/douglas444/nfs-storage:/data
      - /proc/fs/nfsd:/proc/fs/nfsd
    ports:
      - 2049:2049
      - 111:111
