version: "2.1"
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - /home/douglas444/nfs-storage:/data
    ports:
      - 2049:2049