apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-notepad-backend
  namespace: notepad
spec:
  type: kv-v2
  mount: kv
  path: secret/kubernetes/notepad/backend
  destination:
    name: notepad-backend
    create: true
    type: Opaque
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        "mongodb_host":
          text: >-
            {{ .Secrets.mongodb_host }}
        "mongodb_user":
          text: >-
            {{ .Secrets.mongodb_user }}
        "mongodb_password":
          text: >-
            {{ .Secrets.mongodb_password }}
        "oauth2_registration_id":
          text: >-
            {{ .Secrets.oauth2_registration_id }}
        "oauth2_client_id":
          text: >-
            {{ .Secrets.oauth2_client_id }}
        "oauth2_client_secret":
          text: >-
            {{ .Secrets.oauth2_client_secret }}
        "oauth2_scope":
          text: >-
            {{ .Secrets.oauth2_scope }}
  refreshAfter: 30s
  vaultAuthRef: static-auth
