apiVersion: v1
kind: PersistentVolume
metadata:
  name: notepad-db-pv-volume
  labels:
    type: local
spec:
  claimRef:
    name: notepad-db-pv-claim
    namespace: notepad
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/douglas444/nfs-storage/notepad-db_data
    server: blindspot.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notepad-db-pv-claim
  namespace: notepad
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
