apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv-volume
  labels:
      name: local
spec:
  claimRef:
    name: vault-pv-claim
    namespace: vault
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/douglas444/nfs-storage/vault_data
    server: blindspot.local

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pv-claim
  namespace: vault
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi