---
# ClickHouse Data Storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-db-pv-volume
  labels:
    type: local
    role: clickhouse-db
spec:
  storageClassName: clickhouse-nfs-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/douglas444/nfs-storage/honepad-events-projector-db_data
    server: blindspot.local
---
# NFS Storage Class
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-keeper-pv-volume
  labels:
    type: local
    role: clickhouse-keeper
spec:
  storageClassName: clickhouse-nfs-storage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/douglas444/nfs-storage/honepad-events-projector-keeper-db_data
    server: blindspot.local
