apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-drill-backend
  namespace: drill
spec:
  type: kv-v2
  mount: kv
  path: secret/kubernetes/drill/backend
  destination:
    name: drill-backend
    create: true
    type: Opaque
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        "db_url":
          text: >-
            {{ .Secrets.db_url }}
        "db_user":
          text: >-
            {{ .Secrets.db_user }}
        "db_password":
          text: >-
            {{ .Secrets.db_password }}
        "aws_region":
          text: >-
            {{ .Secrets.aws_region }}
        "aws_access_key_id":
          text: >-
            {{ .Secrets.aws_access_key_id }}
        "aws_secret_access_key":
          text: >-
            {{ .Secrets.aws_secret_access_key }}
        "drill_inbound_message_queue_url":
          text: >-
            {{ .Secrets.drill_inbound_message_queue_url }}
        "drill_outbound_message_topic_arn":
          text: >-
            {{ .Secrets.drill_outbound_message_topic_arn }}
  refreshAfter: 30s
  vaultAuthRef: static-auth
