apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-drill-backend
  namespace: drill
spec:
  type: kv-v2
  mount: kv
  path: secret/kubernetes/drill/backend
  destination:
    name: drill-backend
    create: true
    type: Opaque
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        "db-url":
          text: >-
            {{ .Secrets.db-url }}
        "db-user":
          text: >-
            {{ .Secrets.db-user }}
        "db-password":
          text: >-
            {{ .Secrets.db-password }}
  refreshAfter: 30s
  vaultAuthRef: static-auth