apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
type: Opaque
data:
  token: ZXlKaElqb2lNREV3WTJKa1pEZzVZMlF3TkRSbVl6YzVNakkxWXpFM1pUWTBNVGc0WTJNaUxDSjBJam9pTjJJelpURTFZalV0TURrNVl5MDBNMk5sTFdKa1lqUXROalF3WW1VM1lURmpaR1ptSWl3aWN5STZJbHBxVG14T2JWVjZUVlJOZEU1VVFURmFhVEF3VFhwak0weFhTbWhOVkVsMFdXcFpkMDFFYXpWYWJVNXRUVzFTYUNKOQ== 
