apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-cloudflare-tunnel-token
  namespace: cloudflare-tunnel
spec:
  type: kv-v2
  mount: kv
  path: secret/kubernetes/cloudflare/tunnel
  destination:
    name: cloudflare-tunnel-token
    create: true
    type: Opaque
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        "token":
          text: >-
            {{ .Secrets.token }}
  refreshAfter: 30s
  vaultAuthRef: static-auth