apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-volume
  labels:
      name: local
spec:
  claimRef:
    name: kafka-pv-claim
    namespace: kafka
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/douglas444/nfs-storage/kafka_data
    server: blindspot.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pv-claim
  namespace: kafka
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi