apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          valueFrom:
            secretKeyRef:
              name: kafka-ui-secrets
              key: kafka_cluster_0_name
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          valueFrom:
            secretKeyRef:
              name: kafka-ui-secrets
              key: kafka_cluster_0_bootstrapservers
        - name: KAFKA_CLUSTERS_0_METRICS_PORT
          valueFrom:
            secretKeyRef:
              name: kafka-ui-secrets
              key: kafka_cluster_0_metrics_port
        - name: AUTH_TYPE
          value: "LOGIN_FORM"
        - name: SPRING_SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              name: kafka-ui-secrets
              key: ui_username
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-ui-secrets
              key: ui_password
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: kafka-ui
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  selector:
    app: kafka-ui