apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-kafka-ui-secrets
  namespace: kafka-ui
spec:
  type: kv-v2
  mount: kv
  path: secret/kubernetes/kafka-ui
  destination:
    name: kafka-ui-secrets
    create: true
    type: Opaque
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        "kafka_cluster_0_name":
          text: >-
            {{ .Secrets.kafka_cluster_0_name }}
        "kafka_cluster_0_bootstrapservers":
          text: >-
            {{ .Secrets.kafka_cluster_0_bootstrapservers }}
        "kafka_cluster_0_metrics_port":
          text: >-
            {{ .Secrets.kafka_cluster_0_metrics_port }}
  refreshAfter: 30s
  vaultAuthRef: static-auth
